### ISSUE TITLE
Error with spiderable

### ISSUE THREAD

**Issue by civako227** [gadicc/meteor-sitemaps#38]
CPU usage 100% with this error on DigitalOcean

```
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at Object.Package [as handle] (packages/ongoworks_spiderable/packages/ongoworks_spiderable.js:141:1)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at packages/gadicohen_sitemaps/packages/gadicohen_sitemaps.js:71:1
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at Object.Package [as handle] (packages/ongoworks_spiderable/packages/ongoworks_spiderable.js:141:1)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at packages/gadicohen_sitemaps/packages/gadicohen_sitemaps.js:71:1
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:9[IP] 58:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at Object.Package [as handle] (packages/ongoworks_spiderable/packages/ongoworks_spiderable.js:141:1)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at packages/gadicohen_sitemaps/packages/gadicohen_sitemaps.js:71:1
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 

```

**Comment by gadicc** [comment]
Hey, and this doesn't happen without sitemaps?  The "next" on the 2nd last line means sitemaps is not taking responsibility for this request and instead passing it onto the next handler, i.e. spiderable.  See the "errors" section of http://meteorpedia.com/read/spiderable for some tips on figuring this out, spiderable is a pain :D
